// Reference serializer generated by protoc, mirroring make_fixture() in
// main.cpp.  Byte-compares the official implementation against ours.
#include <cstdio>
#include <string>

#include "test.pb.h"

int main()
{
  test::Person p;
  p.set_name("Alice");
  p.set_id(-1);
  p.add_lucky(-3);
  p.add_lucky(7);
  p.set_score(1.5);
  p.mutable_home()->set_city("X");
  p.mutable_home()->set_zip(-2);
  p.set_nick("N");

  std::string s;
  if (!p.SerializeToString(&s))
    return 1;
  std::fwrite(s.data(), 1, s.size(), stdout);
  return 0;
}
