// Reference serializer generated by protoc, mirroring make_fixture() in
// main.cpp.  Byte-compares the official implementation against ours.
#include <cstdio>
#include <string>

#include "test.pb.h"

int main()
{
  test::Person p;
  p.set_name("Alice");
  p.set_id(-1);
  p.add_lucky(-3);
  p.add_lucky(7);
  p.set_score(1.5);
  p.mutable_home()->set_city("X");
  p.mutable_home()->set_zip(-2);
  p.set_nick("N");
  p.set_color(test::GREEN);
  p.add_palette(test::GREEN);
  p.add_palette(test::BLUE);
  p.set_blob("\x01\x02\x03", 3);
  p.set_delta(-5);
  p.set_big(-1234567890123LL);
  p.set_fx32(0xDEADBEEFu);
  p.set_sfx64(-42);
  p.add_samples(-7);
  p.add_samples(1000000);
  p.add_hashes(0xCAFEBABEu);
  p.add_hashes(0x12345678u);
  p.add_flags(true);
  p.add_flags(false);
  p.add_flags(true);
  p.add_tags("a");
  p.add_tags("b");
  (*p.mutable_scores())["alice"] = 3;
  p.add_unpacked_nums(1);
  p.add_unpacked_nums(2);

  std::string s;
  if (!p.SerializeToString(&s))
    return 1;
  std::fwrite(s.data(), 1, s.size(), stdout);
  return 0;
}
